class Place {
  final String id;
  final String category;
  final String name;
  final String description;
  final String fullDescription;
  final String imageUrl;
  final double rating;
  final String price;
  final String location;
  final List<String> tags;

  Place({
    required this.id,
    required this.category,
    required this.name,
    required this.description,
    required this.fullDescription,
    required this.imageUrl,
    required this.rating,
    required this.price,
    required this.location,
    required this.tags,
  });

  static List<Place> getAllPlaces() {
    return [
      Place(
        id: 'a1',
        category: 'nature',
        name: 'Cascades de Karfiguéla',
        description: 'Chutes d\'eau magnifiques près de Banfora.',
        fullDescription: 'Les cascades de Karfiguéla sont l\'un des sites les plus célèbres du Burkina Faso. Nichées au milieu d\'une végétation luxuriante, ces chutes d\'eau offrent un spectacle naturel apaisant. C\'est le lieu idéal pour une baignade rafraîchissante et un pique-nique en famille après avoir exploré les falaises de Banfora.',
        imageUrl: 'https://c7.alamy.com/compfr/2pe7dg7/riviere-cascades-karfiguela-cascades-banfora-province-de-comoe-burkina-faso-2pe7dg7.jpg',
        rating: 4.9,
        price: '2 000 FCFA',
        location: 'Banfora, Cascades',
        tags: ['Nature', 'Baignade', 'Banfora'],
      ),
      Place(
        id: 'a2',
        category: 'culture',
        name: 'Cour Royale de Tiébélé',
        description: 'Architecture traditionnelle Kasséna aux murs peints.',
        fullDescription: 'Découvrez les chefs-d\'œuvre de l\'architecture Kasséna à Tiébélé. Ces habitations traditionnelles en terre sont magnifiquement décorées de fresques géométriques réalisées à la main par les femmes du village. Un témoignage unique du patrimoine culturel et artistique du sud du pays.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Tiebele_village_in_Burkina_Faso_02.jpg/960px-Tiebele_village_in_Burkina_Faso_02.jpg',
        rating: 4.8,
        price: '3 000 FCFA',
        location: 'Tiébélé, Centre-Sud',
        tags: ['Culture', 'Architecture', 'UNESCO'],
      ),
      Place(
        id: 'a3',
        category: 'nature',
        name: 'Pics de Sindou',
        description: 'Formations rocheuses millénaires sculptées par le vent.',
        fullDescription: 'Les Pics de Sindou sont une chaîne de formations gréseuses aux formes fantastiques, façonnées par l\'érosion au fil des millénaires. C\'est l\'un des paysages les plus mystiques du Burkina Faso, offrant des points de vue exceptionnels.',
        imageUrl: 'https://thumbs.dreamstime.com/z/sindou-pics-de-%C3%A0-l-ouest-du-burkina-faso-3635254.jpg?ct=jpeg',
        rating: 4.9,
        price: '2 500 FCFA',
        location: 'Sindou, Cascades',
        tags: ['Randonnée', 'Photographie', 'Géologie'],
      ),
      Place(
        id: 'a4',
        category: 'nature',
        name: 'Lac de Tangréla',
        description: 'Connu pour ses hippopotames.',
        fullDescription: 'Situé au cœur de Ouagadougou, ce restaurant emblématique vous propose le meilleur de la cuisine burkinabè. Goûtez à notre spécialité : le poulet bicyclette braisé aux épices locales.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/77/Image_du_Lac_de_Tingrela_vu_pirogues.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Banfora, Cascades',
        tags: ['Faune', 'Hippopotames', 'Pirogue'],
      ),
      Place(
        id: 'a5',
        category: 'nature',
        name: 'Les Ruines de Loropéni',
        description: 'Forteresse médiévale inscrite au patrimoine mondial de l\'UNESCO.',
        fullDescription: 'Inscrites au patrimoine mondial de l\'UNESCO depuis 2009, les Ruines de Loropéni constituent le premier site du Burkina Faso à avoir reçu cette distinction.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/2016.05-441-131ap_wall_Lorop%C3%A9ni_Ruins_nr.Lorop%C3%A9ni%28Poni_Prv.%29%2CBF_sun15may2016-1106h.jpg/960px-2016.05-441-131ap_wall_Lorop%C3%A9ni_Ruins_nr.Lorop%C3%A9ni%28Poni_Prv.%29%2CBF_sun15may2016-1106h.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Gaoua, Ouest',
        tags: ['UNESCO', 'Histoire', 'Archéologie'],
      ),
      Place(
        id: 'a6',
        category: 'culture',
        name: 'Grande Mosquée de Bobo-Dioulasso',
        description: 'Architecture soudanaise.',
        fullDescription: 'L\'édifice se distingue par ses murs en banco renforcés par des poutres de bois saillantes et ses minarets en forme de cônes ou de pains de sucre.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Moschee_von_Bobo-Dioulasso.jpg/960px-Moschee_von_Bobo-Dioulasso.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Bobo-Dioulasso',
        tags: ['Architecture', 'Religion', 'Patrimoine'],
      ),
      Place(
        id: 'a7',
        category: 'nature',
        name: 'Parc urbain Bangr Weogo',
        description: 'Réserve naturelle en pleine ville.',
        fullDescription: 'Considéré comme le « poumon vert » de Ouagadougou, le Parc Urbain Bangr-Wéogo est un espace forestier aménagé de plus de 240 hectares situé au cœur de la capitale.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/SENTIER_PEDESTRE_A_BANGRE_WEOGO.jpg/960px-SENTIER_PEDESTRE_A_BANGRE_WEOGO.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Détente', 'Forêt', 'Sport'],
      ),
      Place(
        id: 'a8',
        category: 'nature',
        name: 'Dômes de Fabedougou',
        description: 'Formations géologiques.',
        fullDescription: 'Il s\'agit d\'un ensemble de roches sédimentaires (grès) vieilles de plusieurs centaines de millions d\'années. Leur forme conique particulière résulte de l\'érosion causée par le vent et l\'eau.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Domes_de_Fabedougou.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Banfora, Cascades',
        tags: ['Géologie', 'Randonnée', 'Paysage'],
      ),
      Place(
        id: 'a9',
        category: 'nature',
        name: 'Mare aux crocodiles sacrés de Sabou',
        description: 'Site culturel et naturel.',
        fullDescription: 'Les mares aux crocodiles sacrés au Burkina Faso sont des sites touristiques et culturels majeurs. Ces crocodiles du Nil, vénérés et considérés comme des totems protecteurs, cohabitent pacifiquement avec les villageois.',
        imageUrl: 'https://api.chicfaso.com/api/v1/products/file/1fa63ead-5e1e-4380-bb64-0b1e0f678384',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Sabou, Centre-Ouest',
        tags: ['Crocodiles', 'Totem', 'Tradition'],
      ),
      Place(
        id: 'a10',
        category: 'nature',
        name: 'La Guinguette (forêt de Kou)',
        description: 'Lieu de détente près de Bobo-Dioulasso.',
        fullDescription: 'La guinguette est un espace écotouristique situé sur la rive gauche du marigot Kou entre les villages de Nasso et Konkorowé.',
        imageUrl: 'https://scontent.foua1-1.fna.fbcdn.net/v/t39.30808-6/485137366_1086337310180028_4237236784167535225_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=7b2446&_nc_ohc=ssDNLraRRFIQ7kNvwHiU57U&_nc_oc=AdnLm2xzFpoJKhupJZENTHPi1ik1fkXbSaZLdJPxwjDBXThU7cDKAWS6nokNfoBl-Ag&_nc_zt=23&_nc_ht=scontent.foua1-1.fna&_nc_gid=5LEp3Adw4GbXsVfOcmhjvA&_nc_ss=8&oh=00_AfzKDQz0wohjxbvdIvO0kH1UhGTwjC2habfqnHUY_wBcpw&oe=69B142C9',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Bobo-Dioulasso, Nord-Ouest',
        tags: ['Écotourisme', 'Rivière', 'Détente'],
      ),
      Place(
        id: 'a11',
        category: 'culture',
        name: 'Sites de métallurgie ancienne du fer',
        description: 'Classés par l\'UNESCO.',
        fullDescription: 'Les sites de métallurgie ancienne du fer du Burkina Faso sont un ensemble de cinq sites comportant des restes de bas fourneaux de l\'Âge du fer, des vestiges de mines et des traces d\'habitations.',
        imageUrl: 'https://www.wakatsera.com/wp-content/uploads/2019/07/m%C3%A9tallurgie-ancienne-d%E2%80%99extraction-du-fer.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Régions Nord et Centre-Nord',
        tags: ['UNESCO', 'Archéologie', 'Fer'],
      ),
      Place(
        id: 'a12',
        category: 'nature',
        name: 'Source de la rivière Kou',
        description: 'Plan d\'eau naturel près de Bobo-Dioulasso.',
        fullDescription: 'Elle est située à 21 kilomètres à l\'Ouest de Bobo-Dioulasso dans la forêt classée de Kou. C\'est un plan d\'eau naturel formant une sorte de piscine sur le cours de la rivière de Kou.',
        imageUrl: 'https://images.unsplash.com/photo-1665332561290-cc6757172890?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Bobo-Dioulasso, Ouest',
        tags: ['Baignade', 'Nature', 'Forêt'],
      ),
      Place(
        id: 'a13',
        category: 'culture',
        name: 'Musée de Manéga',
        description: 'Musée privé d\'art et de traditions.',
        fullDescription: 'Le musée de Manéga, officiellement appelé musée de la Bendrologie de Manéga, est un musée privé situé à Manéga, dans la province d\'Oubritenga au Burkina Faso.',
        imageUrl: 'https://lh3.googleusercontent.com/gps-cs-s/AHVAwepsTD4Un5V29yXY163O3wCY2HnOK5LoIEF4eYQjvG6v_lsU9UGFo5X2LI48vqpVmme5ESTqFaQZiu_ptfoRkGMg_YgvOCouSKMPp1gpwSqDl3B-5YZWoIjzt9zSQgNhNSpPtaJu=s680-w680-h510-rw',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Manéga, Oubritenga',
        tags: ['Musée', 'Artisanat', 'Traditions'],
      ),
      Place(
        id: 'a14',
        category: 'nature',
        name: 'Grotte de Diébougou',
        description: 'Anciennes structures militaires souterraines.',
        fullDescription: '« La guerre Dinguè » est un site pas trop connu. Son histoire raconte que cet ensemble de grottes abris auraient été construites par l\'armée française ou par l\'administration coloniale.',
        imageUrl: 'https://lepays.bf/wp-content/uploads/2016/07/4940269134_dea89458fc_b.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Commune de Diébougou',
        tags: ['Grottes', 'Histoire', 'Coloniale'],
      ),
      Place(
        id: 'a15',
        category: 'culture',
        name: 'Mémorial Thomas Sankara',
        description: 'Lieu de mémoire historique.',
        fullDescription: 'Le mémorial Thomas-Sankara est un mémorial situé à Ouagadougou, dédié à la mémoire du président burkinabé Thomas Sankara, érigé sur le site du Conseil de l\'Entente.',
        imageUrl: 'https://lh3.googleusercontent.com/gps-cs-s/AHVAweqVv4jFSoxhTFbKX0J1prUAfn7vVIi3llDsOT7cnaa3rYACEZ68RL1VQ4iWXs81yNVQ2_8ZmWSlC3F1YaStQic7GZpQ3kHrTTm3qrfCqBD-EHTz7uklOfrf3wHmT4-rYUTwt3NF=s680-w680-h510-rw',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Mémorial', 'Histoire', 'Politique'],
      ),
      Place(
        id: 'a16',
        category: 'culture',
        name: 'Musée national du Burkina Faso',
        description: 'Histoire et culture.',
        fullDescription: 'Le musée national du Burkina Faso est un établissement culturel situé à Ouagadougou, la capitale du Burkina Faso.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Ouagadougou-Mus%C3%A9e_national_du_Burkina_Faso_%281%29.jpg/960px-Ouagadougou-Mus%C3%A9e_national_du_Burkina_Faso_%281%29.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Musée', 'Culture', 'Histoire'],
      ),
      Place(
        id: 'a17',
        category: 'nature',
        name: 'Parc animalier de Ziniaré',
        description: 'Faune africaine.',
        fullDescription: 'Le parc animalier de Ziniaré est un parc zoologique situé à Ziniaré, à environ trente kilomètres de Ouagadougou.',
        imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/A_l%27entr%C3%A9e_du_parc_animalier_de_ZINIAR%C3%89.jpg/960px-A_l%27entr%C3%A9e_du_parc_animalier_de_ZINIAR%C3%89.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ziniaré, Plateau-Central',
        tags: ['Zoo', 'Faune', 'Famille'],
      ),
      Place(
        id: 'a18',
        category: 'nature',
        name: 'Complexe W-Arly-Pendjari (Est)',
        description: 'Aires protégées pour l\'observation de la faune.',
        fullDescription: 'Le complexe W-Arly-Pendjari est un site naturel transfrontalier classé au patrimoine mondial de l\'UNESCO, situé au Bénin, au Burkina Faso et au Niger.',
        imageUrl: 'https://whc.unesco.org/uploads/thumbs/site_0749_0007-600-600-20170607180434.webp',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Frontière Burkina-Bénin',
        tags: ['UNESCO', 'Safari', 'Faune'],
      ),
      Place(
        id: 'a19',
        category: 'culture',
        name: 'SIAO',
        description: 'Salon International de l\'Artisanat de Ouagadougou.',
        fullDescription: 'Le SIAO est une manifestation qui rassemble des artisans venus du monde entier. L\'artisanat africain est toutefois généralement à l\'honneur. Il a lieu chaque deux ans.',
        imageUrl: 'https://www.artistesbf.org/wp-content/uploads/2024/11/siao-770x540.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Artisanat', 'Festival', 'International'],
      ),
      Place(
        id: 'a20',
        category: 'culture',
        name: 'FESPACO',
        description: 'Festival panafricain du cinéma et de la télévision.',
        fullDescription: 'Le FESPACO est l\'un des plus grands festivals de cinémas en Afrique. Créé en 1969, il se déroule tous les deux ans à Ouagadougou.',
        imageUrl: 'https://faso7.com/wp-content/uploads/2021/01/Fespaco-Palais-photo_1-e1723141089519-780x470.jpg',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Cinéma', 'Festival', 'Panafricain'],
      ),

      // Restaurants
      Place(
        id: 'r1',
        category: 'food',
        name: 'Le Gourmet du Faso',
        description: 'Le temple du Poulet Bicyclette et du Riz Gras.',
        fullDescription: 'Situé au cœur de Ouagadougou, ce restaurant emblématique vous propose le meilleur de la cuisine burkinabè. Goûtez à notre spécialité : le poulet bicyclette braisé aux épices locales.',
        imageUrl: 'https://images.unsplash.com/photo-1665332561290-cc6757172890?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.6,
        price: '8 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Burkinabè', 'Grillades', 'Populaire'],
      ),
      Place(
        id: 'r2',
        category: 'food',
        name: 'Restaurant Le Verdoyant',
        description: 'Cuisine locale dans un cadre verdoyant.',
        fullDescription: 'Le Verdoyant est un restaurant en plein air proposant des spécialités burkinabè dans un cadre naturel apaisant.',
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.3,
        price: '6 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Terrasse', 'Burkinabè', 'Famille'],
      ),
      Place(
        id: 'r3',
        category: 'food',
        name: 'Maquis Chez Fatou',
        description: 'Maquis populaire au cœur de Bobo.',
        fullDescription: 'Chez Fatou est l\'un des maquis les plus populaires de Bobo-Dioulasso, connu pour ses grillades et son ambiance conviviale.',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.4,
        price: '5 000 FCFA',
        location: 'Bobo-Dioulasso, Hauts-Bassins',
        tags: ['Maquis', 'Grillades', 'Convivial'],
      ),
      Place(
        id: 'r4',
        category: 'food',
        name: 'Restaurant Le Diplomate',
        description: 'Cuisine internationale et burkinabè.',
        fullDescription: 'Le Diplomate propose une carte variée alliant cuisine internationale et spécialités locales dans un cadre élégant.',
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.5,
        price: '12 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['International', 'Élégant', 'Affaires'],
      ),
      Place(
        id: 'r5',
        category: 'food',
        name: 'La Cabane Bambou',
        description: 'Spécialités de poisson frais.',
        fullDescription: 'La Cabane Bambou est spécialisée dans les poissons frais du fleuve, grillés sur braises selon les recettes traditionnelles burkinabè.',
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.2,
        price: '7 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Poisson', 'Braises', 'Traditionnel'],
      ),
      Place(
        id: 'r6',
        category: 'food',
        name: 'Resto-Bar Le Kaïcédrat',
        description: 'Bar-restaurant sous les arbres.',
        fullDescription: 'Le Kaïcédrat est un espace de restauration en plein air installé sous de grands arbres, idéal pour déguster des plats locaux dans une atmosphère décontractée.',
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.1,
        price: '4 500 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Bar', 'Plein air', 'Décontracté'],
      ),
      Place(
        id: 'r7',
        category: 'food',
        name: 'Restaurant Saveurs d\'Afrique',
        description: 'Cuisine panafricaine.',
        fullDescription: 'Saveurs d\'Afrique propose des plats issus de plusieurs cuisines africaines, avec une forte mise en valeur des produits locaux du Burkina Faso.',
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.3,
        price: '9 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Panafricain', 'Découverte', 'Varié'],
      ),
      Place(
        id: 'r8',
        category: 'food',
        name: 'Pizzeria Chez Mario',
        description: 'Pizzas artisanales à Ouagadougou.',
        fullDescription: 'Chez Mario propose des pizzas artisanales cuites au feu de bois, mêlant recettes italiennes et touches locales burkinabè.',
        imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.0,
        price: '6 500 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Pizza', 'Italien', 'Feu de bois'],
      ),
      Place(
        id: 'r9',
        category: 'food',
        name: 'Maquis La Détente',
        description: 'Ambiance festive et brochettes.',
        fullDescription: 'La Détente est un maquis animé proposant brochettes, poulet yassa et bières locales dans une ambiance musicale chaque soir.',
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.2,
        price: '5 500 FCFA',
        location: 'Bobo-Dioulasso, Hauts-Bassins',
        tags: ['Brochettes', 'Musique', 'Festif'],
      ),
      Place(
        id: 'r10',
        category: 'food',
        name: 'Restaurant Le Baobab',
        description: 'Cuisine traditionnelle sous le baobab.',
        fullDescription: 'Le Baobab est un restaurant thématique qui met à l\'honneur les recettes ancestrales du Burkina Faso dans un décor authentique.',
        imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.4,
        price: '7 500 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Traditionnel', 'Authentique', 'Burkinabè'],
      ),
      Place(
        id: 'r11',
        category: 'food',
        name: 'Snack Le Délice',
        description: 'Sandwichs et jus de fruits frais.',
        fullDescription: 'Le Délice est un snack rapide proposant sandwichs garnis, jus de fruits frais et pâtisseries locales, idéal pour une pause gourmande.',
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 3.9,
        price: '2 500 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Rapide', 'Jus', 'Snack'],
      ),
      Place(
        id: 'r12',
        category: 'food',
        name: 'Restaurant Le Fleuve',
        description: 'Vue sur le fleuve Mouhoun.',
        fullDescription: 'Le restaurant Le Fleuve offre une vue imprenable sur le fleuve Mouhoun tout en proposant des spécialités de poissons et de viandes grillées.',
        imageUrl: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.5,
        price: '10 000 FCFA',
        location: 'Dédougou, Boucle du Mouhoun',
        tags: ['Vue fleuve', 'Poisson', 'Romantique'],
      ),
      Place(
        id: 'r13',
        category: 'food',
        name: 'Brasserie du Faso',
        description: 'Grande brasserie au centre-ville.',
        fullDescription: 'La Brasserie du Faso est un établissement de restauration proposant une cuisine variée dans un cadre moderne et climatisé au cœur de Ouagadougou.',
        imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.1,
        price: '8 500 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Brasserie', 'Climatisé', 'Varié'],
      ),
      Place(
        id: 'r14',
        category: 'food',
        name: 'Chez la Maman Burkinabè',
        description: 'Cuisine maison authentique.',
        fullDescription: 'Chez la Maman Burkinabè, on mange comme à la maison. Tô, sauce graine, haricots rouges et riz gras sont servis avec générosité.',
        imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.6,
        price: '3 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Maison', 'Tô', 'Économique'],
      ),
      Place(
        id: 'r15',
        category: 'food',
        name: 'Jardin Restaurant Wend-Panga',
        description: 'Détente et gastronomie en plein air.',
        fullDescription: 'Le Jardin Wend-Panga est un espace de restauration gastronomique en plein air proposant des plats burkinabè revisités dans un cadre fleuri et paisible.',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.4,
        price: '11 000 FCFA',
        location: 'Ouagadougou, Centre',
        tags: ['Jardin', 'Gastronomie', 'Paisible'],
      ),
      Place(
        id: 'r16',
        category: 'food',
        name: 'Resto Couleurs du Sahel',
        description: 'Saveurs du nord du Burkina.',
        fullDescription: 'Couleurs du Sahel met en valeur les spécialités culinaires du nord du Burkina Faso : couscous de mil, viande de chameau et thé touareg.',
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&q=80&w=1080',
        rating: 4.3,
        price: '7 000 FCFA',
        location: 'Ouahigouya, Nord',
        tags: ['Sahel', 'Couscous', 'Nordiste'],
      ),
    ];
  }
}