// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KHTZMRc7M040tuI1BODpxfskcfDLqno',
    appId: '1:430764301843:web:950f32de9083f5c20569e6',
    messagingSenderId: '430764301843',
    projectId: 'faso-tourisme',
    authDomain: 'faso-tourisme.firebaseapp.com',
    storageBucket: 'faso-tourisme.firebasestorage.app',
    measurementId: 'G-FPGW2TW99G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKpx1MlfBC77IF7uhlCGeVqGXsUQaTOI',
    appId: '1:430764301843:android:bac3099288695d320569e6',
    messagingSenderId: '430764301843',
    projectId: 'faso-tourisme',
    storageBucket: 'faso-tourisme.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDFo0lqd2Hd4YyRoZlFf3GNHq3maxma0',
    appId: '1:430764301843:ios:7edc238af09916bc0569e6',
    messagingSenderId: '430764301843',
    projectId: 'faso-tourisme',
    storageBucket: 'faso-tourisme.firebasestorage.app',
    iosClientId: '430764301843-856imla8tm94vbjv2ngaj4gn9v7dhjur.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasoTourisme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KHTZMRc7M040tuI1BODpxfskcfDLqno',
    appId: '1:430764301843:web:8c68c50c37fc5b230569e6',
    messagingSenderId: '430764301843',
    projectId: 'faso-tourisme',
    authDomain: 'faso-tourisme.firebaseapp.com',
    storageBucket: 'faso-tourisme.firebasestorage.app',
    measurementId: 'G-F3W04WCW3Z',
  );
}
